### ISSUE TITLE
Feature_mainPage: 씨앗의 상태 변화 오류

### ISSUE THREAD

**Issue by minseonju** [luminous037/OSS_project#100]
**물을 준 횟수에 따라서 씨앗의 상태가 변화합니다.**
모달 창을 열어서 씨앗을 선택해 씨앗 심기 -> 씨앗 상태(물 준 횟수 1회) -> 꽃 상태(물 준 횟수 2회) -> 나무 상태(물 준 횟수 3회) - > 보상이 열린 나무 상태(물 준 횟수 4회)

**씨앗에 물을 주기 위해서 먼저 거쳐야 하는 선행 단계가 있습니다.**
약을 먹고 clear 버튼 누르기(한번 누를 때마다 35%만큼 퍼센테이지가 증가함) -> 구름 퍼센테이지 100%까지 채우기(100%를 채우기 위해서는 clear 버튼을 3번 눌러야 함) -> 100%까지 찬 구름 클릭해서 비 내리기 

**현재 clear 버튼이 메인페이지에도 있고 알람 창 페이지에도 있습니다.
메인 페이지에 있는 clear 버튼을 이용해 구름을 채우고 비를 내리면 씨앗이 위에서 말한 순서대로 상태 변화가 적절하게 나타납니다.
하지만 알람 창 페이지에 있는 clear 버튼을 이용해 구름을 채우고 비를 내리면 씨앗의 상태가 항상 씨앗 상태(물을 준 회수 1회)인 상태로 돌아갑니다.**

**Comment by GAUDUL** [comment]
메인페이지가 렌더링될때마다 물 퍼센티지가 계속 초기화되는 것은 아닐까요

아직 코드는 확인 못해서 자세한 답변은 불가능하겠지만
서버 작업이 완료되면 해결될 문제 같습니다
