### ISSUE TITLE
Feature_shop : 프록시 오류 again

### ISSUE THREAD

**Issue by luminous037** [luminous037/OSS_project#102]
@minseonju 전에 올리셨던 오류랑 같은 오류 메세지가 떠서 같은 오류인 것 같은데, 어떻게 해결하셨었나요?
<img width="744" alt="image" src="https://github.com/luminous037/OSS_project/assets/135002121/4f3af0e2-0cf3-43e7-b4c5-6b654643b054">

**Comment by minseonju** [comment]
https://github.com/luminous037/OSS_project/issues/53
해당 이슈 참고하시면 될거 같습니다.
