### ISSUE TITLE
!서버 데이터 연동 시 주목할 사항!

### ISSUE THREAD

**Issue by GAUDUL** [luminous037/OSS_project#107]
제가 지금까지 데이터들을 연동해 본 결과,
DB에 저장한 대부분의 데이터들은 useState로 관리되던 데이터들이었습니다.
물론 다른 방식이 가능할 수도 있겠지만 아직 그런 사례가 없어서요..

그런 의미로 혹시 db에 저장될 데이터들은 useState로 관리해주셨으면 합니다.

지금 제 예상 db 구조도는 다음과 같습니다

![image](https://github.com/luminous037/OSS_project/assets/137772044/93378330-db8b-4d49-a4de-d29380fc6412)

**Comment by GAUDUL** [comment]
혹시 수정하고 싶으신 사항이 있으시다면 댓글 달아주세요

**Comment by GAUDUL** [comment]
아 데이터베이스에선 mediList가 아니고 medicineList로 작성해놨습니다

**Comment by GAUDUL** [comment]
mediList에서
detail은 복용법에 관련된 내용입니다

**Comment by luminous037** [comment]
알겠습니다

**Comment by GAUDUL** [comment]
plantWaterPercent -> cloud 로 변경
