### ISSUE TITLE
Feature_infoPage: 코드 수정

### ISSUE THREAD

**Issue by GAUDUL** [luminous037/OSS_project#108]
서버 연결을 하려고 했는데 코드가 복잡해서 어디서부터 손을 봐야할 지 모르겠습니다....

현재 infoPage2는 제가 조금 손봐서 코드를 정리해놨는데
해당 코드를 토대로 infoPage3도 정리해주실 수 있나요??

따로 하나씩 관리하던 useState 구문들을 하나로 묶어주시면 됩니다.
기왕이면 연관성 있는 것들끼리요!

이 편이 더 작성하기 쉽고 알아보기도 더 쉬우실 거에요!

**Comment by GAUDUL** [comment]
pr 올릴테니 해당 내용 토대로 infoPage 요청사항들도 수정해주시면 감사하겠습니다!

**Comment by GAUDUL** [comment]
infoPage 요청 사항
: 약 이름 설정, 알람 설정 인터페이스 수정

**Comment by luminous037** [comment]
약 이름 설정 기능 넣었습니다
<img width="515" alt="image" src="https://github.com/luminous037/OSS_project/assets/135002121/cbc5d6e0-2998-4925-96b5-7e808fe063c4">

**Comment by GAUDUL** [comment]
감사합니다

**Comment by GAUDUL** [comment]
@luminous037 

제가 infoPage_1 에서 받은 사용자의 이름을
infoPage_2에서 출력되도록 했는데
그 부분 css도 작성해주실 수 있나요

infoPage_2 의 134번째 줄입니다.

      <div className="background2">
        <h1>{childName}</h1>
      </div>

**Comment by GAUDUL** [comment]
아 그리고
infoPage_3에서

알람 설정 여부를 묻는 부분이 있는데

거기서 alarm 설정 여부를 정하지 않은 상태에서 다음 버튼을 누를 시 경고 창이 뜨도록 구현되었으면 좋겠습니다.
