### ISSUE TITLE
Feature_alarm: 푸시 알람 기본 세팅

### ISSUE THREAD

**Issue by GAUDUL** [luminous037/OSS_project#110]
푸시 알람에 관련된 자료들을 읽고 이를 구현하기 위한 기본 세팅을 시작하겠습니다.

**Comment by luminous037** [comment]
네 알겠습니다람쥐

**Comment by GAUDUL** [comment]
npm install firebase

**Comment by minseonju** [comment]
푸쉬 알림은 firebase를 이용해서 구현할건가요??

**Comment by GAUDUL** [comment]
네 firebase 사용하게 될 것 같습니다.

**Comment by GAUDUL** [comment]
npm install firebase-admin
