### ISSUE TITLE
Feature: 이전페이지로 이동하는 버튼 만들기 하려고 하는데 도와주세요

### ISSUE THREAD

**Issue by luminous037** [luminous037/OSS_project#125]
@GAUDUL 님이 썼던 방식으로 (Info1에서 Info2로 넘어가는 버튼) 모든 페이지 (상점, 칭찬스티커 페이지, Info페이지) 뒤로가는 버튼을 만드려고 합니다. 제가 Info2 -> Info3 으로 이동하는 버튼을 @GAUDUL 님 코드 보고 같은 방식으로 쓰려고 했는데 잘 동작하지 않았습니다. 혹시 코드 설명이나 조언 해주실 수 있을까요?

**Comment by GAUDUL** [comment]
혹시 어떻게 작성하셨는지 알 수 있을까요

제가 썼던 방식이라면 아마 useNavigate를 이용한 방식 같은데

  const navigate=useNavigate();   (import {useNavigate} from 'react-router-dom'; 해야함)

이렇게 선언해 둔 뒤
 navigate('경로');
 작성해주시면 됩니다.
 
혹시 이렇게 작성했는데도 작동이 안되신 거라면
자세한 코드를 확인해봐야 알 것 같습니다.
