### ISSUE TITLE
Start 스플래시 화면 오류? 있습니다.

### ISSUE THREAD

**Issue by luminous037** [luminous037/OSS_project#126]
<img width="515" alt="image" src="https://github.com/luminous037/OSS_project/assets/135002121/e4cb8d08-7d18-42e5-a853-3d412a7ceb17">
코드 수정 필요해보입니다.

**Comment by luminous037** [comment]
@minseonju

**Comment by minseonju** [comment]
index.js 파일에서 랜더링을 두번시켜서 생긴 문제입니다. 오류 수정하겠습니다.
