### ISSUE TITLE
Feature: MyPage 약 복용시간 입력받는 방식을 info3과 동일하게 바꿔야 할까요?

### ISSUE THREAD

**Issue by luminous037** [luminous037/OSS_project#127]
현재 mypage css 작업중입니다만, 설정한 시간 재설정 화면에서 Info3과 설정 방법이 다른거 같아 질문드립니다. Info3에서 시간을 받는 방법과 동일하게 js 코드를 수정할까요?
info3의 방식은 아래와 같습니다. (코드 input type="number")
<img width="316" alt="image" src="https://github.com/luminous037/OSS_project/assets/135002121/ce4377e8-6885-4859-9548-947395547468">

**Comment by luminous037** [comment]
@GAUDUL

**Comment by luminous037** [comment]
+ 지금 <설정한 시간>이 설정한 시간을 바꾸는 기능이 아니라 전에 설정한 시간을 확인하는 용도임을 지금 코드를 보고 확인했습니다. 그러면 시간을 재설정하는 기능은 넣지 않을 생각이셨는지요?

**Comment by GAUDUL** [comment]
제가 약 상세 정보관련 페이지를 2개 만들었는데요

하나는 약을 추가할 때 사용하는 페이지고 (AddMedi
하나는 약 목록 클릭 시 나타나는, 사용자가 입력한 정보를 보여주는 페이지입니다. (PageCanvas [DetailPage]

<결론>
AddMedi 에선 infoPage_3 과 동일하게 알람 시간을 설정할 수 있다면 좋겠고

PageCanvas에선 따로 시간을 재설정하는 기능을 넣을 예정이 없습니다.
그러므로 PageCavas에선 AddMedi와는 유사하나 따로 수정을 할 수는 없도록 구현이 되었으면 좋겠습니다.
