### ISSUE TITLE
Feature_server: 메인과의 연결 이후 오류

### ISSUE THREAD

**Issue by GAUDUL** [luminous037/OSS_project#130]
현재 작성하신 코드를 바탕으로 데이터베이스와 연결을 한 결과

데이터들은 잘 저장이 되었는데
씨앗을 심은 상태에서 물을 줘도 계속해서 자라지가 않습니다...

혹시 server브랜치의 코드를 한 번 살펴보신 후, 뭐가 문제인지 조언을 얻을 수 있을까요

**Comment by minseonju** [comment]
로컬 저장소에 데이터를 저장했을 때는 출력값이 문제 없이 잘 나타났던 것을 보면 씨앗 상태를 나타내는 조건문에는 문제가 없는 것으로 보입니다. 혹시 몽고 디비와 연결하는 과정에서 어떤 코드를 바꿨는지 알 수 있을까요?

**Comment by GAUDUL** [comment]
일단 이제 물을 주면 자라기는 합니다만,
새로고침을 해야 바뀐 모습이 보이네요

**Comment by minseonju** [comment]
해당 문제 해결했습니다. seed.js에서 씨앗의 상태를 나타내는 조건문에 문제가 있었던게 아니라 main.js에서 seed.js에 있는 함수들을 prop 형식으로 받아오는데 문제가 있었습니다.
