### ISSUE TITLE
Feature_infoPage : 네비게이터를 통해 이동한 infopage_2 가 출력되지 않음

### ISSUE THREAD

**Issue by luminous037** [luminous037/OSS_project#14]
infoPage_1.js 에서 infoPage_2.js 로 Link사용한 네비게이터로 이동하면 localhost:3000/infoPage_1/infoPage_2 로 이동되어서 기능이 화면에 부려오지 않습니다.
localhost:3000/infoPage_2 일 땐 기능이 화면에 정상적으로 출력됨.

**Comment by minseonju** [comment]
navigaition 기능을 구현한 페이지에서 이동할 페이지의 주소가 정확히 명시 되었는지 확인해 주세요.

**Comment by luminous037** [comment]
해결 했습니다
