### ISSUE TITLE
Feature_weekly : 칭찬스티커 다 모으면 포인트 주기

### ISSUE THREAD

**Issue by luminous037** [luminous037/OSS_project#140]
칭찬스티커를 다 모으면 포인트를 부여하는 모달창이 자동으로 뜨게 하는 기능,
모달창에서 포인트 받기를 누르면 포인트가 올라가도록 DB에 연결하는 작업이 필요합니다.
저는 일단 모달창을 띄우는 기능 코드부터 작성하곘습니다

**Comment by GAUDUL** [comment]
확인했습니다
