### ISSUE TITLE
Feature_main : 하루에 한 번 칭찬스티커 부여하는 모달 (출석체크 개념)

### ISSUE THREAD

**Issue by luminous037** [luminous037/OSS_project#142]
Main 페이지에서) 하루에 한 번 출석체크를 하는 개념으로 모달창을 띄우고, 칭찬스티커 획득 버튼을 포함하도록 해서 누르면 칭찬스티커 페이지로 이동하며, 누르는 동시에 칭찬스티커를 부여하는 기능을 추가하려고 합니다.

**Comment by GAUDUL** [comment]
기대됩니다.
