### ISSUE TITLE
Feature_main : 나무상태로 자라면 다른페이지로 이동할 수 없습니다. (네비게이션 바가 가려져서)

### ISSUE THREAD

**Issue by luminous037** [luminous037/OSS_project#151]
<img width="501" alt="image" src="https://github.com/luminous037/OSS_project/assets/135002121/3d6958db-fbe5-45ca-afe4-a2f079a4d30e">
그림은 나무로 자란 상태에서 네비게이션 바가 가려진 모습입니다.

식물이 자라는 과정에서 이미지 크기가 모두 달라 컨테이너가 점점 내려갑니다.
아마 CSS 에서 이미지 클래스 포지션을 absolute로 해주시거나 아니면 이미지들의 크기를 다 동일하게 맞춰주시면 해결 될 듯 합니다. 
수정 부탁드립니다.

**Comment by minseonju** [comment]
이미지의 크기를 조정하는 것은 이미지가 너무 작아질거 같아서 안될거 같습니다. 포지션을 
absolute로 해도 다른 요소들의 크기가 네비게이션바를 침범하기 때문에 해결되지 않습니다.

**Comment by minseonju** [comment]
해당 문제를 해결하기 위해서는 z-index를 다른 요소들의 z-index보다 크게 설정해주면 됩니다.
