### ISSUE TITLE
ReadMe 파일에 적을 모듈 목록

### ISSUE THREAD

**Issue by GAUDUL** [luminous037/OSS_project#159]
yarn 전역 설치
npm install
npm install dotenv
npm install node-cron
npm install firebase-admin
npm install firebase (클라이언트)
npm install express
npm install concurrently --save-dev ( 서버)

**Comment by minseonju** [comment]
1. node.js 설치 방법
2. mongoDB 연결 방법

3. firebase 연결 방법도 필요할까요??

**Comment by GAUDUL** [comment]
1번 2번은 안써도 될 거 같고
firebase쪽은 명시를 해줘야 할 거 같습니다!

**Comment by GAUDUL** [comment]
firebase 관련 내용은 다음과 같습니다

1. firebase 콘솔에서 프로젝트 생성
2. 프로젝트 설정에서 SDK 설정 env 파일에 저장 (파일 형식은 제공할 것)
3. 프로젝트 설정의 서비스 계정에서 비공개 키 다운
4. 위 2,3 번 내용의 파일을 서버 폴더에 저장

**Comment by minseonju** [comment]
.env 파일이랑 serviceappcountkey.json 파일도 처음 레포를 복제했을 때 없는데 이도 명시해야 할까요?
