### ISSUE TITLE
Feature_startPage: ui/ux 디자인 수정

### ISSUE THREAD

**Issue by minseonju** [luminous037/OSS_project#17]
**startPage의 디자인을 변경하고 싶습니다.**

초기의 어플의 목적은 물 마시는 양을 관리해주는 것이어서
어플 시작 시 가장 먼저 보게되는 startpage를 물과 연관된 이미지로 디자인 했습니다. 

하지만 주제를 어린이들이 약을 먹는 것을 도와주는 어플로 바꾸었기에 바뀐 주제에 맞추어서 ui/ux 디자인도 수정하고 싶습니다.
상단에서 떨어지는 물방울을 없애고 병아리 캐릭터 근처에 알약이 떠오르는 것으로 바꾸면 어떨까요?

![startpage ui 변경사항](https://github.com/luminous037/OSS_project/assets/138373881/e9ef38b6-3353-46d1-9236-af979d085aa9)

![Uploading startpage ui 변경사항.png…]()

**Comment by luminous037** [comment]
좋아요!! 그런데 알약의 색깔이 아이들의 눈을 더 끌도록 알록달록 했으면 좋겠네요.

**Comment by minseonju** [comment]
네 알겠습니다.

**Comment by minseonju** [comment]
그럼 의견을 수렴해서 바꾼 디자인으로 다시 작업하겠습니다.
