### ISSUE TITLE
Feature_mainPage: bottomnavigationbar 구현

### ISSUE THREAD

**Issue by minseonju** [luminous037/OSS_project#3]
**여러 페이지 간의 이동이 가능한 navigationbar를 구현하기**

- navigationbar의 위치는 화면의 하단에 고정함.
- navigationbar으로 이동할 수 있는 페이지는 홈(메인), 캘린더, 상점, 마이페이지(설정), 게임 페이지로 구분함.

**Comment by minseonju** [comment]
**navigationbar가 두가지 종류가 있는데 무엇으로 할까요??**
1. stack을 이용한 navigationbar
2. 일반적인 navigationbar(스택을 이용한 뒤로가기 기능 등 불가)

**Comment by GAUDUL** [comment]
1번이 좋을 거 같아요

**Comment by luminous037** [comment]
뒤로 가기 기능 필요해요

**Comment by minseonju** [comment]
그럼 1번으로 구현할게요!
