### ISSUE TITLE
InfoPage1,2,3: CSS 파일 제작

### ISSUE THREAD

**Issue by luminous037** [luminous037/OSS_project#31]
<img width="317" alt="image" src="https://github.com/luminous037/OSS_project/assets/135002121/d008882d-e0af-4af2-9a51-bf5f3dd80499">
<img width="315" alt="image" src="https://github.com/luminous037/OSS_project/assets/135002121/47f57726-830f-48f5-b10b-48bbca20d5a1">
<img width="314" alt="image" src="https://github.com/luminous037/OSS_project/assets/135002121/5e82e990-8057-4ad6-9739-390e58fb628a">
위 프로토타입 대로 CSS 제작하려 합니다.
위에서 부터 각각 InfoPage 1, 2, 3 입니다.
폰트와 세부적인 요소의 위치는 변경될 수 있습니다.

**Comment by minseonju** [comment]
사용자가 어플을 시작했을 때 가장 먼저 보이는 페이지의 전체적인 색감이 파란색이니깐 첫 페이지는 파란색으로 하고 두번째는 파란색과 초록색 반반, 세번째는 초록색으로 하는거 어때요??
<img width="492" alt="스크린샷 2024-05-01 오후 11 33 45" src="https://github.com/luminous037/OSS_project/assets/138373881/4ef91376-1eee-43db-9e61-a3ec0a0f5b0a">
<img width="492" alt="스크린샷 2024-05-01 오후 11 33 45" src="https://github.com/luminous037/OSS_project/assets/138373881/d7a4bd33-c3e5-470f-9b7c-0015d1e2fe2b">

**Comment by luminous037** [comment]
그냥 전부 파랑으로 바꿀까요?

**Comment by luminous037** [comment]
지금 작업하려고 하는데 파랑으로 바꿀까요? @minseonju

**Comment by GAUDUL** [comment]
파랑도 좋다고 생각합니다!

**Comment by minseonju** [comment]
색 변경하는 것은 간단한 작업이니 둘 다 해보고 더 통일성있는 색상으로 선택하는 것도 좋을거 같아요
