### ISSUE TITLE
Feature_server: 데이터베이스에 들어가야 할 데이터 정리

### ISSUE THREAD

**Issue by GAUDUL** [luminous037/OSS_project#33]
각자 자기 페이지에 필요한 데이터들을 정리해서 올려주세요

ex) Mypage : 사용자가 적은 약에 대한 정보(약 이름, 약 복용 시간 등)

**Comment by minseonju** [comment]
**1. alarmpage:** 사용자가 알람 받기로 지정한 시간에 대한 정보(오전/오후, 몇시 몇분)

**2. mainpage:** 사용자가 일주일 중 몇 일동안 약을 잘 먹었는지에 대한 정보 / 나무에 물을 준 횟수(7번 물을 주면 나무에 보상이 열림) / 사용자가 보유하고 있는 씨앗의 종류와 갯수 / 사용자가 보유하고 있는 재화의 종류와 갯수 / 사용자가 보유하고 있는 특수 아이템의 종류와 갯수

**Comment by luminous037** [comment]
InfoPgae_1, InfoPgae_2, InfoPgae_3 : 사용자 이름, 복용방법과 시간, 알람 설정여부
WeeklyCheckPage : 메인에서 출석한 여부에 따라 칭찬스티커 띄우기, 칭찬스티커 갯수 저장
Shop: 모인 포인트 저장, 상점에서 파는 아이템 구매한건지 안한건지 저장

**Comment by GAUDUL** [comment]
넵 확인했습니다
감사합니다
