### ISSUE TITLE
Feature_myPage: 약 목록 삭제 버튼 및 알람 on/off 버튼 추가

### ISSUE THREAD

**Issue by GAUDUL** [luminous037/OSS_project#40]
휴지통 모양의 약 목록 삭제 버튼과 알람 on/off 버튼을 추가하여 이후 서버에서 해당 작업을 수행할 수 있도록 하겠습니다.

**Comment by luminous037** [comment]
약 종류에 따른 목록을 등록 하는지는 몰랐는데요,

**Comment by luminous037** [comment]
어떤 상황에서 필요하게 되는 기능인가요?

**Comment by GAUDUL** [comment]
사용자가 꼭 한 가지의 약만 먹는다는 보장이 없기에, 자신이 먹는 약들을 등록하도록 만든 겁니다.

이후 약을 안먹게 되는 순간이 오면 그 땐 삭제 기능이 필요하겠죠.

**Comment by luminous037** [comment]
확인했습니다

**Comment by GAUDUL** [comment]
구현 완료 했습다
