### ISSUE TITLE
Feature_server: 서버 요청 관련

### ISSUE THREAD

**Issue by GAUDUL** [luminous037/OSS_project#44]
자신이 만든 페이지의 기본적인 기능 구현이 완료되어, 
이후의 작업은 서버에 요청을 해야 하거나 서버에게서 데이터를 받아와야 진행되는 페이지의 경우 답글로 달아주세요.

해당 페이지에서 정확히 어떤 작업이 필요한지도 기재해주시면 감사하겠습니다.

**Comment by luminous037** [comment]
InfoPage_1 (아이 이름 받기 페이지) : 여기서 받은 이름이 다음 InfoPage_2에서 출력되도록 해야합니다. 그리고 앞으로 이름이 표시되어야 할 곳마다 출력되야 합니다.
InfoPage_2 (약 처방 정보 입력 페이지): 약 복용법에 대한 정보가 마이페이지에 저장되어야 하며, 여기서 아침, 점심, 저녁 체크 여부에 따라 다음 InfoPage_3 : 에서 기본 설정 알람의 시간에 반영되어야 합니다. (아침, 점심, 저녁을 체크 하였을 경우 기본 알람 설정 오전 8시, 오후 1시, 오후 6시 이런식으로.) 기본 알람 설정 시간은 나중에 논의해 봅시다. 
localhost:3000/InfoPage_1 들어가시면 볼 수 있어요.

**Comment by minseonju** [comment]
mainPage: 일주일 동안 약을 잘 챙겨먹은 횟수를 퍼센트로 변환하여 나타낼 예정입니다. 구름 디자인 안에 퍼센트를 나타내고 퍼센트가 커질수록 빈상태에서 점점 채워지는 형식으로 구현할 것입니다.
보상으로 받은 씨앗을 심고 물을 준 횟수에 따라서 씨앗의 성장 상태를 다르게 나타낼 예정입니다. 최종 성장 상태가 되기 위해서는 총 7번 물을 주어야 합니다.

alarmPage: 사용자가 지정한 시간마다 약을 먹어야 한다는 알람이 노래와 함께 울려야 하며, clear 버튼을 눌렀을 경우 알람 창이 꺼져야합니다.

추가적으로 필요한 사항이 생길 경우 추후 추가하겠습니다.
