### ISSUE TITLE
Feature_myPage: 약 관련 정보 입력에 대한 질문

### ISSUE THREAD

**Issue by GAUDUL** [luminous037/OSS_project#46]
현재 약 상세 정보 페이지를 작성하는 중, 사용자가 입력하는 약 정보와 관련해 궁금증이 생겨 질문 드립니다!

luminous 님 같은 경우 
약 복용법에 대해
아침, 점심, 저녁, 그리고 식전, 식후 이렇게 나눠서 정리하셨는데

사용자가 정한 시간에 알람이 가는 거면 사용자는 알람이 온 시간에 약을 먹게 될 텐데,
식전, 식후, 아침 , 점심, 저녁 이런 식으로 복용법을 나누는게 의미가 있을까요??
아니면 혹시 다른 의도가 있으신 걸까요?

약 정보 관련하여 어떤 정보들을 사용자로부터 받을 것인지 확실히 정하고자 합니다!

**Comment by luminous037** [comment]
물론 알림창, 그리고 마이페이지에서도 확인할 수 있도록 하면 좋구요.

**Comment by GAUDUL** [comment]
아하 그럼 메모 같은 용도로 이용하신 거군요

**Comment by GAUDUL** [comment]
확인했습니다!

**Comment by GAUDUL** [comment]
혹시 더 추가하고 싶은 내용이 있으시다면 답글 달아주세요

**Comment by minseonju** [comment]
그럼 최종적으로 정리해 보면 사용자 기본 설정을 할 경우 식전 식후를 정하고 오후 오전을 정하고 구체적인 시간을 정하는 순서대로 진행되는 건가요?
만약 먹는 약이 여러 종류일 경우 식전 약일 수도 있고 식후 약일 수도 있으니 luminous님 말씀처럼 해당 정보를 알려주는 것도 좋을 것 같아요.

**Comment by GAUDUL** [comment]
넵 알겠습니다.
해당 내용 토대로 수정하겠습니다!
