### ISSUE TITLE
파일 정리

### ISSUE THREAD

**Issue by luminous037** [luminous037/OSS_project#48]
페이지마다 사용한 코드와 png 파일은 한 파일에 묶에서 보관해주세요
src > components > InfoPage(생성)

<img width="140" alt="image" src="https://github.com/luminous037/OSS_project/assets/135002121/fb102f1e-e8a2-4856-896c-64eabda042bd">

**Comment by GAUDUL** [comment]
png 파일들은
src파일말고 public에 넣어도 될 거 같아요

**Comment by minseonju** [comment]
파일 정리 후 경로 수정 잊지말고 해주세요

**Comment by luminous037** [comment]
네네치킨
