### ISSUE TITLE
MyPage: 실행 오류?

### ISSUE THREAD

**Issue by luminous037** [luminous037/OSS_project#49]
@GAUDUL 머지하신 MyPage.js 에서 문제가 있다고 npm이 실행이 안됩니다.
해결방법 알려주세요.

<img width="641" alt="image" src="https://github.com/luminous037/OSS_project/assets/135002121/5ddb59f6-a831-49b5-8ecb-1d575f66b213">

**Comment by GAUDUL** [comment]
client에 가서
npm install react-switch
하셔야 합니다

**Comment by luminous037** [comment]
잘 작동 되네요.
