### ISSUE TITLE
Feature_guidebookPage: 사용 설명창에 들어갈 내용 정리

### ISSUE THREAD

**Issue by minseonju** [luminous037/OSS_project#51]
**사용자에게 간단한 사용 방법과 각 페이지에 존재하는 기능에 대해서 알려주는 설명창을 만들고자 합니다**

각 페이지 별로 해당 페이지가 담고 있는 기능과 설명을 간단하게 작성해주세요.

사용 설명 창은 각 페이지 별로 만들 예정이며 사용 설명창 아래에 위치한 화살표를 누르면 다른 페이지에 대한 설명 창으로 넘어갈 수 있습니다.

<img width="481" alt="스크린샷 2024-05-09 오후 5 21 08" src="https://github.com/luminous037/OSS_project/assets/138373881/b23e0f25-5185-4689-ba3d-437a5fb21a2c">

**Comment by GAUDUL** [comment]
마이페이지:
자신의 이름과 알림 설정 상태 그리고 현재 자신의 약 목록을 확인할 수 있는 페이지입니다.
쓰레기통 아이콘을 눌러 해당되는 행의 약의 정보를 삭제할 수 있고,
약 목록 하단의 + 버튼을 눌러 약을 추가할 수 있습니다.

**Comment by minseonju** [comment]
페이지 별 ui 이미지 파일 보내주세요

**Comment by luminous037** [comment]
<img width="317" alt="image" src="https://github.com/luminous037/OSS_project/assets/135002121/8c7a4069-359a-41af-9c24-d5a5d2d60337">
<img width="318" alt="image" src="https://github.com/luminous037/OSS_project/assets/135002121/d412b1a6-77dd-4921-b60d-38f953bb6ae7">

**Comment by luminous037** [comment]
![image](https://github.com/luminous037/OSS_project/assets/135002121/2449857d-2b9e-4012-8e13-cc50339d9c96)![image](https://github.com/luminous037/OSS_project/assets/135002121/4d707884-b95f-4842-9005-84f34f774739![image](https://github.com/luminous037/OSS_project/assets/135002121/35c85e65-6648-4f69-a2c3-c48fcbfc7d51)

**Comment by GAUDUL** [comment]
![image](https://github.com/luminous037/OSS_project/assets/137772044/3a84e2dc-64bb-492e-b8d6-caf023dda8cb)
![image](https://github.com/luminous037/OSS_project/assets/137772044/582ab1e7-d2e0-4130-9474-b393ddc4e791)

**Comment by minseonju** [comment]
구현 완료했습니다.
