### ISSUE TITLE
Feature_guidebookPage: 프록시 오류

### ISSUE THREAD

**Issue by minseonju** [luminous037/OSS_project#53]
**사용 설명 텍스트 밑에 이미지가 나와야 하지만 나오지 않음**

**터미널 확인해 본 결과 프록시 오류가 뜸**
<img width="505" alt="스크린샷 2024-05-09 오후 7 06 20" src="https://github.com/luminous037/OSS_project/assets/138373881/bb7388fd-3c0f-4f4e-88a2-24fa6cd29930">

<img width="734" alt="스크린샷 2024-05-09 오후 7 09 36" src="https://github.com/luminous037/OSS_project/assets/138373881/5d1de672-9a80-4e87-9b42-314617409c1b">

**Comment by minseonju** [comment]
해당 기능을 구현할 때 서버를 사용하는 일이 없는데 왜 프록시 오류가 뜰까요??

**Comment by GAUDUL** [comment]
자세한 코드를 확인해봐야 알 거 같습니다.
오류가 난 부분을 알려주실 수 있나여

**Comment by minseonju** [comment]
제가 지금까지 작성한 코드 중에서 서버가 이용되는 부분이 없는데 저런 오류가 뜨는 것 같아요. 코드는 guidebook.js 와 main.js 파일을 참고해 주세요

**Comment by minseonju** [comment]
데이터 베이스 권한을 받지 않아 생긴 오류라고 판단되어 권한을 받은 후 다시 실행해 보았지만 오류가 해결되지 않았습니다. 슬라이드 기능에 대한 코드 자체를 수정하는 방식으로 오류 해결 진행하겠습니다.

**Comment by GAUDUL** [comment]
좀 늦은 감이 있지만

**Comment by GAUDUL** [comment]
이미지 파일을 public 파일에 넣고

            <img src="/addButton.png" alt="Add Button"/>
            
 이와 같이 작성하니 전 잘 작동했습니다.

**Comment by GAUDUL** [comment]
react에선 public 폴더가 정적 파일을 호스팅하는데 사용된다고 하네요
그래서 이미지 파일을 public 폴더 안에 넣으면 프록시 서버 요청 필요 없이 정적으로 제공된다고 합니다.
참고하시길 바랍니다.

**Comment by luminous037** [comment]
js에서 이미지 파일을 불러와 쓰려고 할 땐 자신의 상위 폴더 (src) 밖의 폴더인 public 폴더의 경로는 사용할 수 없다고 뜹니다.

**Comment by minseonju** [comment]
그래서 저는 src/components/image/image.png 경로에 이미지를 다 저장해 놓긴 했습니다. luminous님 말씀대로라면 public 폴더로 이미지 경로를 수정해도 오류가 해결되지 않으니 코드를 다시 작성하는 방법으로 해결했습니다.

**Comment by GAUDUL** [comment]
@luminous037 
혹시 src에 상대경로로 작성하셨나요

저기선 절대경로로 해야 오류가 안생깁니다

**Comment by GAUDUL** [comment]
public에 이미지 넣어두셨으면 
"/(이미지파일.png" 
로 접근하시면 됩니다
