### ISSUE TITLE
Feature_server: 데이터 저장 요청 관련

### ISSUE THREAD

**Issue by GAUDUL** [luminous037/OSS_project#56]
제가 데이터를 저장할 때 따로 함수를 만들어서 저장하기 때문에

만일 데이터를 저장하고자 하신다면 저장 버튼을 따로 구현하시거나,
다음 페이지로 넘어가면서 저장하고자 하신다면 Link 컴포넌트가 아닌 button 요소를 이용하여 onClick 함수로 구현해주세요.

Link 컴포넌트 안에는 핸들러를 적용할 수가 없어 이동하면서 저장을 할 수가 없습니다.

**Comment by luminous037** [comment]
현재 페이지 PR 후 수정하겠습니다!

**Comment by GAUDUL** [comment]
넵 감사합니다
