### ISSUE TITLE
Feature_myPage: 약 목록 추가 및 삭제 기능

### ISSUE THREAD

**Issue by GAUDUL** [luminous037/OSS_project#6]
마이페이지에서 약 목록 추가 및 삭제 기능 작업 시작하겠습니다.

● 구현 방법 
 1. 연결리스트 이용
 2. 배열 이용

**Comment by GAUDUL** [comment]
아마도 1번 방법으로 먼저 시도하게 될 거 같습니다

**Comment by minseonju** [comment]
두가지 방법의 장단점을 알 수 있을까요?
저장할 데이터의 양이 많지 않다면 구현하기 쉬운 방법으로 해도 좋을거 같습니다.

**Comment by GAUDUL** [comment]
약 목록 안에 이름, 복용 시간, 복용 방법 등을 넣을 예정이어서 구조체를 활용하는게 나을 거 같기도 하고,
아무래도 삭제 기능도 있다 보니까 삭제가 편리한 연결리스트가 더 좋을 거 같습니다.

**Comment by GAUDUL** [comment]
useState와 데이터베이스를 활용한 결과, 데이터베이스에서 데이터를 삭제하니 배열에서도 그냥 잘 삭제되더라고요.
연결리스트를 활용안해도 될 거 같습니다!
