### ISSUE TITLE
Feature_shop : 상점 데이터 서버와 연동하기 위한 코드작성 좋은생각 있으신가요

### ISSUE THREAD

**Issue by luminous037** [luminous037/OSS_project#79]
상점에는 저장되어야 할 것이 사용자의 포인트 갯수와 사용자가 상점에 있는 아이템을 샀던 아이템인지, 아직 사지 않은 아이템인지가 반영되어야 합니다.
나중에 서버와 연결하기 좋게 코드를 작성해야 할 것 같은데, 어떤방식으로 하면 좋을까요?

**Comment by GAUDUL** [comment]
useState를 이용해서 해당 아이템의 이름, 가격, 소유 여부, 착용 여부 등을 한번에 다 다룰 수 있도록 하면 좋겠네요
