### ISSUE TITLE
main 실행 오류

### ISSUE THREAD

**Issue by GAUDUL** [luminous037/OSS_project#80]
![image](https://github.com/luminous037/OSS_project/assets/137772044/18f49aa1-b047-4ed3-8d99-241ce6acae66) ![image](https://github.com/luminous037/OSS_project/assets/137772044/e84ace05-8803-489e-abde-8071693a15e1)

Feature_myPage에서 작업을 하다가 pr을 올리기 위해 git pull origin main을 했습니다
따로 충돌이 일어나진 않았으나 혹시 몰라 한번 실행을 해보니 연결이 계속 안된다고 뜨네요
작업할 때까지만 해도 잘 접속됐었는데 말이죠..
심지어 터미널 창을 보면 제대로 포트도 작동하고 있고 DB연결도 잘 됐습니다.

그래서 나도 모르는 충돌이 생길걸까?

해서 따로 현재 main을 clone하여 실행을 해봤는데
위의 사진과 똑같이 나타납니다
main에 문제가 있는 거 같은데 다른 분들은 잘 실행되나요?

**Comment by GAUDUL** [comment]
확인 결과 main에 있는 server폴더의 package.json 파일 내용에 문제가 있었습니다.

어쩌다 서버의 내용이 누락되었는지는 모르겠습니다만.. package.json 파일 내용만 수정하면 될 거 같습니다

**Comment by luminous037** [comment]
뭘 수정해야되나요?

**Comment by GAUDUL** [comment]
제가 새로 작성 후 메인에 다시 넣겠습니다

**Comment by GAUDUL** [comment]
해결 완료했습니다
