### ISSUE TITLE
혹시 서버 데이터와 연결해서 작성한 페이지 있으신 분 있나요?

### ISSUE THREAD

**Issue by luminous037** [luminous037/OSS_project#87]
페이지가 기본적으로 생성은 다 된 상태라 서버 연결하면서 세부적인 코드 수정이 필요할 것 같습니다. 서버 연결 해 놓으신 분 있으면 도움 구합니다.

**Comment by GAUDUL** [comment]
현재 infoPage 서버 작업 중입니다
완료되면 pr 올리겠습니다

어떤 기능이 필요하신지는 잘 모르겠지만, 급하시다면 
현재 MyPage 폴더의 MyPageCP.js 파일을 한번 확인해보시길 바랍니다.

**Comment by minseonju** [comment]
서버랑 연결하기 전에 데이터가 잘 저장되는지 확인하고 싶으시면 일단 로컬 저장소에 저장하는 방법도 있습니다.

**Comment by GAUDUL** [comment]
https://github.com/luminous037/OSS_project/issues/107

item 부분 참고해주세요
