### ISSUE TITLE
Feature_infoPage : 약 이름 저장

### ISSUE THREAD

**Issue by GAUDUL** [luminous037/OSS_project#99]
@luminous037 
info 페이지 2 에서 약 이름을 입력하는 칸은 따로 존재하지 않는데
일부러 그러신건가요?

사용자가 자신이 입력한 약에 대한 정보를 더 알아보기 쉽게
약 이름을 입력하는 칸이 따로 있었으면 좋겠습니다만...

**Comment by luminous037** [comment]
넣어드리겠습니다. 지금 shop 브랜치 작업중이라, 지금 당장 수정 필요할까요??

**Comment by GAUDUL** [comment]
가능한 빨리 작업해주시면 감사하겠습니다
